### ISSUE TITLE
Upgrade all usages of clj-http to use forked client

### ISSUE THREAD

**Issue by tvanhens** [Stedi-Public-Archive/clj-http#2]

**Comment by grammati** [comment]
This involves changing usages of clj-http.client to use stedi.aws.http instead, from the stedi/aws-api project. This has already been done for calls to netsuite from node-netsuite, but not yet in other places.

**Comment by grammati** [comment]
This has been added to StediInc/aws-api. There are other issues to track switching to our aws-api in various services, so I'll close this issue.
